//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2018 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2018.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +10
        ///-9
        ///+12
        ///+5
        ///+13
        ///-6
        ///-19
        ///-4
        ///-17
        ///-1
        ///+7
        ///+18
        ///-13
        ///-15
        ///-6
        ///-11
        ///-12
        ///-9
        ///+12
        ///+2
        ///+14
        ///+11
        ///+17
        ///-10
        ///-21
        ///+6
        ///+18
        ///-4
        ///-16
        ///+15
        ///+8
        ///+13
        ///+12
        ///+4
        ///-1
        ///-19
        ///-7
        ///+14
        ///+8
        ///-3
        ///+5
        ///-9
        ///+16
        ///-11
        ///+21
        ///-3
        ///+23
        ///-8
        ///-16
        ///+11
        ///-3
        ///+1
        ///+16
        ///-3
        ///+14
        ///-9
        ///+17
        ///+5
        ///-3
        ///+17
        ///+12
        ///+19
        ///-12
        ///-14
        ///+13
        ///-3
        ///+6
        ///+15
        ///+18
        ///-8
        ///+14
        ///+14
        ///+3
        ///+18
        ///+4
        ///-9
        ///+12
        ///+6
        ///+8
        ///+18
        ///+12
        ///+13
        ///-6
        ///-13
        ///-13
        ///-17
        ///+14
        ///-3
        ///+2
        ///+12
        ///-6
        ///+16
        ///-9
        ///+6
        ///-1
        ///-4
        ///+17
        ///+9
        ///+6
        ///-3
        ///+9
        ///-15
        ///-11
        ///-17
        ///+7
        ///-9
        ///-18
        ///-21
        ///+2
        ///-11
        ///+12
        ///-21
        ///-8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1
        ///+1
        ///+1.
        /// </summary>
        internal static string Day01Puzzle1Sample1 {
            get {
                return ResourceManager.GetString("Day01Puzzle1Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1
        ///+1
        ///-2.
        /// </summary>
        internal static string Day01Puzzle1Sample2 {
            get {
                return ResourceManager.GetString("Day01Puzzle1Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1
        ///-2
        ///-3.
        /// </summary>
        internal static string Day01Puzzle1Sample3 {
            get {
                return ResourceManager.GetString("Day01Puzzle1Sample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1
        ///-1.
        /// </summary>
        internal static string Day01Puzzle2Sample1 {
            get {
                return ResourceManager.GetString("Day01Puzzle2Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3
        ///+3
        ///+4
        ///-2
        ///-4.
        /// </summary>
        internal static string Day01Puzzle2Sample2 {
            get {
                return ResourceManager.GetString("Day01Puzzle2Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6
        ///+3
        ///+8
        ///+5
        ///-6.
        /// </summary>
        internal static string Day01Puzzle2Sample3 {
            get {
                return ResourceManager.GetString("Day01Puzzle2Sample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7
        ///+7
        ///-2
        ///-7
        ///-4.
        /// </summary>
        internal static string Day01Puzzle2Sample4 {
            get {
                return ResourceManager.GetString("Day01Puzzle2Sample4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fonbsmjyqugrapsczckghtvdxl
        ///fonpsmjyquwrnpeczikghtvdxw
        ///fonbsmdymuwrapexzikghtvdxl
        ///fonwsmjyquwrapeczikghttdpl
        ///fonbsmjkquwrapeczjkghtvdxx
        ///yonbsmjyquwrapecgikghtvdxc
        ///donbsmjyquqrapeczikghtadxl
        ///monbsmjyquprgpeczikghtvdxl
        ///fonbsmjyquwvapecqgkghtvdxl
        ///fonbsmjyquwrkphczikghsvdxl
        ///fonbomjyeuwvapeczikghtvdxl
        ///fonwsmjyjuwrapoczikghtvdxl
        ///foybsmjyquwcapeczikghsvdxl
        ///fonbsmjyquwrtaeczikgptvdxl
        ///ponbsmpyquwjapeczikghtvdxl
        ///flnbcmjyquwrqpeczikghtvdxl
        ///fonbsmjyquwrapegzikvbtvdxl
        ///fonbjmjyqgwrazeczikghtvdxl
        ///zoabsmjy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdef
        ///bababc
        ///abbcde
        ///abcccd
        ///aabcdd
        ///abcdee
        ///ababab.
        /// </summary>
        internal static string Day02Puzzle1Sample {
            get {
                return ResourceManager.GetString("Day02Puzzle1Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcde
        ///fghij
        ///klmno
        ///pqrst
        ///fguij
        ///axcye
        ///wvxyz.
        /// </summary>
        internal static string Day02Puzzle2Sample {
            get {
                return ResourceManager.GetString("Day02Puzzle2Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 871,327: 16x20
        ///#2 @ 676,717: 27x26
        ///#3 @ 245,818: 19x21
        ///#4 @ 89,306: 22x11
        ///#5 @ 451,712: 20x11
        ///#6 @ 322,299: 24x29
        ///#7 @ 161,304: 10x29
        ///#8 @ 746,459: 19x25
        ///#9 @ 720,21: 19x29
        ///#10 @ 803,435: 22x20
        ///#11 @ 437,394: 13x29
        ///#12 @ 654,445: 22x25
        ///#13 @ 723,721: 3x10
        ///#14 @ 643,575: 13x28
        ///#15 @ 706,265: 16x18
        ///#16 @ 670,661: 21x21
        ///#17 @ 168,664: 26x15
        ///#18 @ 4,461: 19x29
        ///#19 @ 771,73: 20x29
        ///#20 @ 730,864: 24x12
        ///#21 @ 373,371: 19x27
        ///#22 @ 666,803: 23x17
        ///#23 @ 944,277: 28x12
        ///#24 @ 579,563: 25x13        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 1,3: 4x4
        ///#2 @ 3,1: 4x4
        ///#3 @ 5,5: 2x2.
        /// </summary>
        internal static string Day03Puzzle1Sample {
            get {
                return ResourceManager.GetString("Day03Puzzle1Sample", resourceCulture);
            }
        }
    }
}
